# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Read BED Files
#' 
#' @param bed Name of the BED file.
#' @param obs Total number of subjects in FAM file.
#' @param snp SNP to import.  
#' 
#' @return Numeric vector of genotypes at the selected SNP. 
#' @export 
readbed <- function(bed, obs, snp) {
    .Call('_ReadPlink_readbed', PACKAGE = 'ReadPlink', bed, obs, snp)
}

